language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg-dev libpng12-dev libgif-dev

script: "perl Makefile.PL; TEST_POD=1 make test"
